# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: password
  domain_name: example.com
  secret_key_base: 3d3b85b1b6c22b8df00acf91215a7acf3c727f93e48f8e56bedabc9a64ce3586eb574a61193972bc113292afe4b5aca50b4726e58162a36b6daadc21e408c613

test:
  domain_name: example.com 
  secret_key_base: 1e9bc895c64a7348ec1a3ca0af518ffcb32472cc82843bc177ad4a7acfab91fd98e52d2bf8268b0cdb3a94b004223a59a0e9cdcfc6e1a3a02e559ade80e050e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
